name: docs
channels:
  - defaults
  - conda-forge
  - pytorch
  - pyg
dependencies:
    # Base depends
  - cpuonly
  - pytorch=1.10.1
  - numpy
  - pandas
  - pytest
  - scipy
  - tensorboard
  - tqdm
  - seaborn
  - matplotlib
  - pylint
  - pytest-pylint
  - yapf
  - pyg


    # Pip-only installs
  #- pip:
